### ISSUE TITLE
Invitation email doesn't arrrive

### ISSUE THREAD

**Issue by nesukun** [reactiflux/www#3]
Hi,
Just so you know, I've been trying to register to access the slack group several times to no avail, the inivitation email never arrives (I checked the spam folder too :p)

**Comment by clentfort** [comment]
Slack claims the reactiflux community grew to big for their service and disabled new user creation for the community. See this tweet: https://twitter.com/reactjsnews/status/647194700248559616

**Comment by nesukun** [comment]
Thanks, I haven't noticed that, could be useful to place a notice message in the registration page in the meantime.

**Comment by bcbcarl** [comment]
I have to same problem. Do you have IRC channel?

**Comment by benhollander** [comment]
Any followup on this?

**Comment by benigeri** [comment]
http://reactiflux.com We're now on Discord.
